import os
import subprocess
import requests

def get_git_diff():
    try:
        subprocess.run(["git", "fetch", "origin", "main"], check=True)
        diff = subprocess.check_output(
            ["git", "diff", "origin/main...HEAD"], 
            text=True
        )
        return diff
    except Exception as e:
        print("Error fetching diff:", e)
        return ""

def main():
    diff_text = get_git_diff()
    if not diff_text.strip():
        print("No code changes found in diff.")
        with open("pr_review.md", "w", encoding="utf-8") as f:
            f.write("✅ **No code changes detected to review.**")
        return

    # Keep diff within safe token boundaries
    diff_sample = diff_text[:12000]

    system_instruction = (
        "You are an Automated Principal Software Engineer and QA Lead reviewing a Pull Request.\n"
        "Follow industry code review best practices (like Cloudflare and Meta).\n\n"
        "Analyze this git diff carefully:\n\n"
        + diff_sample + "\n\n"
        "Respond strictly in GitHub Markdown using these exact headings:\n"
        "### ⚡ Executive Summary of Changes\n"
        "- 2 to 3 bullet points summarizing what was added or changed.\n\n"
        "### 🛡️ Security, Bugs & Edge-Cases\n"
        "- Highlight any SQL injection, missing input sanitization, zero division, or null safety issues.\n"
        "- If completely safe, write 'No critical vulnerabilities detected.'\n\n"
        "### 🧪 Automated Unit Test Recommendations\n"
        "- Provide complete, runnable unit test code (e.g., PyTest) covering happy path and edge/negative cases.\n\n"
        "---\n*Generated by AI SDLC Quality Gate Bot*"
    )

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("GEMINI_API_KEY is missing from environment.")
        return

    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" + api_key
    payload = {
        "contents": [{"parts": [{"text": system_instruction}]}]
    }

    try:
        res = requests.post(url, json=payload, timeout=60)
        res_data = res.json()
        review_body = res_data["candidates"][0]["content"]["parts"][0]["text"]
    except Exception as err:
        review_body = "⚠️ **AI Reviewer Error:** Could not parse AI response.\nDetails: `" + str(err) + "`"

    with open("pr_review.md", "w", encoding="utf-8") as f:
        f.write(review_body)

if __name__ == "__main__":
    main()
