import os
import subprocess
import requests

def get_git_diff():
    try:
        subprocess.run(["git", "fetch", "origin", "main"], check=True)
        diff = subprocess.check_output(
            ["git", "diff", "origin/main...HEAD"], 
            text=True
        )
        return diff
    except Exception as e:
        print("Error fetching diff:", e)
        return ""

def main():
    diff_text = get_git_diff()
    if not diff_text.strip():
        print("No code changes found in diff.")
        with open("pr_review.md", "w", encoding="utf-8") as f:
            f.write("✅ **No code changes detected to review.**")
        return

    diff_sample = diff_text[:8000]

    system_instruction = (
        "You are an Automated Principal Software Engineer and QA Lead reviewing a Pull Request.\n"
        "Analyze this git diff carefully:\n\n"
        + diff_sample + "\n\n"
        "Respond strictly in GitHub Markdown using these exact headings:\n"
        "### ⚡ Executive Summary of Changes\n"
        "- 2 to 3 bullet points summarizing what was added or changed.\n\n"
        "### 🛡️ Security, Bugs & Edge-Cases\n"
        "- Highlight any SQL injection, missing input sanitization, zero division, or null safety issues.\n"
        "- If completely safe, write 'No critical vulnerabilities detected.'\n\n"
        "### 🧪 Automated Unit Test Recommendations\n"
        "- Provide complete, runnable unit test code (e.g., PyTest) covering happy path and edge/negative cases.\n\n"
        "---\n*Generated by AI SDLC Quality Gate Bot*"
    )

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        with open("pr_review.md", "w", encoding="utf-8") as f:
            f.write("⚠️ **Configuration Error:** `GEMINI_API_KEY` secret is not configured in repository settings.")
        return

    # Use current active models with automatic fallback
    candidate_models = ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-2.5-pro"]
    payload = {
        "contents": [{"parts": [{"text": system_instruction}]}]
    }

    review_body = None
    last_err = ""

    for model_name in candidate_models:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
        try:
            res = requests.post(url, json=payload, timeout=45)
            res_data = res.json()
            if "candidates" in res_data and len(res_data["candidates"]) > 0:
                review_body = res_data["candidates"][0]["content"]["parts"][0]["text"]
                break
            elif "error" in res_data:
                last_err = res_data.get("error", {}).get("message", str(res_data))
        except Exception as e:
            last_err = str(e)

    if not review_body:
        review_body = f"⚠️ **Gemini API Error:** `{last_err}`"

    with open("pr_review.md", "w", encoding="utf-8") as f:
        f.write(review_body)

if __name__ == "__main__":
    main()
